/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package git.lib

import kotlin.test.Test
import kotlin.test.assertTrue

class GitTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Git()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
